// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Channel struct {
	ID     string  `json:"id"`
	URL    *string `json:"url"`
	Origin *Origin `json:"origin"`
}

type Header struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type MetaData struct {
	Time    string    `json:"time"`
	Tags    []*string `json:"tags"`
	Headers []*Header `json:"headers"`
}

type NewPost struct {
	Subject string `json:"subject"`
	Body    string `json:"body"`
	UserID  string `json:"userId"`
}

type Origin struct {
	ID  string  `json:"id"`
	URL *string `json:"url"`
}

type Post struct {
	ID       string    `json:"id"`
	Channel  *Channel  `json:"channel"`
	User     *User     `json:"user"`
	Subject  string    `json:"subject"`
	Body     string    `json:"body"`
	Metadata *MetaData `json:"metadata"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
